import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CookieConsent from "./components/CookieConsent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        {children}
        <footer className="border-t mt-auto py-6 text-sm text-gray-500">
          <div className="max-w-5xl mx-auto px-4 flex flex-col sm:flex-row gap-2 sm:gap-4 items-start sm:items-center justify-between">
            <p>
              © {new Date().getFullYear()} Mon Restaurant. Tous droits réservés.
            </p>
            <nav className="flex flex-wrap items-center gap-4">
              <Link href="/mentions-legales" className="hover:underline">Mentions légales</Link>
              <Link href="/politique-de-confidentialite" className="hover:underline">Politique de confidentialité</Link>
              <Link href="/cookies" className="hover:underline">Cookies</Link>
            </nav>
          </div>
        </footer>
        <CookieConsent />
      </body>
    </html>
  );
}
